export const MONTHLY_EXPENSES_COPY = {
  pageTitle: 'Despesas mensais',
  monthlySpending: 'Gastos do mês',
  budget: 'Orçamento',
  remainingBalance: 'Saldo restante',
  goalsAndFixed: 'Metas + fixos',
  salaryAndCards: (salary: string, cards: string) => `Salário ${salary} + cartões ${cards}`,
  availableFromSalary: 'Disponível do salário',
  aboveSalary: 'Acima do salário',
  transactions: 'Transações',
  newTransaction: 'Nova transação',
  noTransactions: 'Nenhuma transação neste mês.',
  noTransactionsFound: 'Nenhuma transação encontrada.',
  myCards: 'Meus cartões',
  switchCard: 'Trocar cartão',
  addCard: 'Adicionar cartão',
  noCards: 'Nenhum cartão cadastrado',
  addFirstCard: 'Adicione seu primeiro cartão',
  addFirstCardHint: 'Use o botão Adicionar cartão para acompanhar limite e uso mensal.',
  selectedCard: 'Cartão selecionado',
  limitUsed: 'Limite usado',
  limitOf: (limit: string) => `de ${limit}`,
  currentInvoice: 'Fatura atual',
  noInvoice: 'Sem fatura',
  dueOn: (date: string) => `Vence em ${date}`,
  dueDay: (day: number) => `Dia ${day}`,
  aboveSalaryAvailable: 'Acima do salário disponível.',
  payInvoice: 'Pagar fatura',
  paid: 'Pago',
  pending: 'Pendente',
  showCardFront: 'Mostrar frente do cartão',
  showCardInvoice: 'Mostrar fatura do cartão',
  edit: 'Editar',
  delete: 'Excluir',
  deleteCard: 'Excluir cartão',
  deleteCardHint:
    'As transações deste cartão serão mantidas como Dinheiro e o limite será removido do orçamento.',
  cancel: 'Cancelar',
  saveTransaction: 'Salvar transação',
  saving: 'Salvando…',
  loadError: 'Não foi possível carregar as despesas.',
  toast: {
    expenseCreated: 'Despesa criada.',
    expenseUpdated: 'Despesa atualizada.',
    expenseRemoved: 'Despesa removida.',
    cardPurchaseCreated: 'Compra no cartão registrada.',
    cardPurchaseCancelled: 'Compra no cartão cancelada.',
    transactionRemoved: 'Transação removida.',
    categoryCreated: 'Categoria criada.',
    categoryUpdated: 'Categoria atualizada.',
    categoryRemoved: 'Categoria removida.',
    cardCreated: 'Cartão criado.',
    cardUpdated: 'Cartão atualizado.',
    cardRemoved: 'Cartão removido.',
    invoicePaid: 'Fatura paga.',
  },
} as const;
