export const MONTHLY_EXPENSES_COPY = {
  pageTitle: 'Monthly expenses',
  monthlySpending: 'Monthly spending',
  budget: 'Budget',
  remainingBalance: 'Remaining balance',
  goalsAndFixed: 'Goals + fixed',
  salaryAndCards: (salary: string, cards: string) => `Salary ${salary} + cards ${cards}`,
  availableFromSalary: 'Available from salary',
  aboveSalary: 'Above salary',
  transactions: 'Transactions',
  newTransaction: 'New transaction',
  noTransactions: 'No transactions this month.',
  noTransactionsFound: 'No transactions found.',
  myCards: 'My cards',
  switchCard: 'Switch card',
  addCard: 'Add card',
  noCards: 'No cards registered',
  addFirstCard: 'Add your first card',
  addFirstCardHint: 'Use the Add card button to track limit and monthly usage.',
  selectedCard: 'Selected card',
  limitUsed: 'Limit used',
  limitOf: (limit: string) => `of ${limit}`,
  currentInvoice: 'Current invoice',
  noInvoice: 'No invoice',
  dueOn: (date: string) => `Due on ${date}`,
  dueDay: (day: number) => `Day ${day}`,
  aboveSalaryAvailable: 'Above available salary.',
  payInvoice: 'Pay invoice',
  paid: 'Paid',
  pending: 'Pending',
  showCardFront: 'Show card front',
  showCardInvoice: 'Show card invoice',
  edit: 'Edit',
  delete: 'Delete',
  deleteCard: 'Delete card',
  deleteCardHint:
    'Transactions for this card will be kept as Cash and the limit will be removed from the budget.',
  cancel: 'Cancel',
  saveTransaction: 'Save transaction',
  saving: 'Saving…',
  loadError: 'Could not load expenses.',
  toast: {
    expenseCreated: 'Expense created.',
    expenseUpdated: 'Expense updated.',
    expenseRemoved: 'Expense removed.',
    cardPurchaseCreated: 'Card purchase recorded.',
    cardPurchaseCancelled: 'Card purchase cancelled.',
    transactionRemoved: 'Transaction removed.',
    categoryCreated: 'Category created.',
    categoryUpdated: 'Category updated.',
    categoryRemoved: 'Category removed.',
    cardCreated: 'Card created.',
    cardUpdated: 'Card updated.',
    cardRemoved: 'Card removed.',
    invoicePaid: 'Invoice paid.',
  },
} as const;
