import type { NotificationVm } from '@/components/notifications/notifications-types';

/** Static demo data — replace with API in the future. */
export const STATIC_NOTIFICATIONS: NotificationVm[] = [
  {
    id: 'n-1',
    category: 'finance',
    kind: 'alert',
    priority: 'urgent',
    title: 'Food budget at 83%',
    body: 'You have spent R$ 1,240 of R$ 1,500 this month. Review before exceeding the limit.',
    timeLabel: '8 min ago',
    read: false,
    href: '/monthly-expenses',
    ctaLabel: 'View expenses',
  },
  {
    id: 'n-2',
    category: 'goals',
    kind: 'insight',
    priority: 'normal',
    title: 'Goal "Emergency reserve" — +R$ 500',
    body: 'Contribution recorded. R$ 5,800 left to complete the goal.',
    timeLabel: '35 min ago',
    read: false,
    href: '/finance-goals',
    ctaLabel: 'View goal',
  },
  {
    id: 'n-3',
    category: 'tasks',
    kind: 'reminder',
    priority: 'normal',
    title: '3 pending tasks today',
    body: 'You still have tasks scheduled to complete before the end of the day.',
    timeLabel: '1 h ago',
    read: false,
    href: '/create-tasks',
    ctaLabel: 'Open tasks',
  },
  {
    id: 'n-4',
    category: 'training',
    kind: 'reminder',
    priority: 'normal',
    title: 'Leg day scheduled',
    body: "Today's plan includes leg training at 6:00 PM.",
    timeLabel: '2 h ago',
    read: false,
    href: '/training-area',
    ctaLabel: 'View workout',
  },
  {
    id: 'n-5',
    category: 'wallet',
    kind: 'update',
    priority: 'low',
    title: 'Wallet updated',
    body: 'Your BTC position value rose 2.4% in the last 24 hours.',
    timeLabel: '3 h ago',
    read: false,
    href: '/wallet-investments',
    ctaLabel: 'View wallet',
  },
  {
    id: 'n-6',
    category: 'diet',
    kind: 'reminder',
    priority: 'normal',
    title: 'Water goal at 60%',
    body: '800 ml left to reach your daily hydration goal.',
    timeLabel: '4 h ago',
    read: false,
    href: '/diet-area',
    ctaLabel: 'Log water',
  },
  {
    id: 'n-7',
    category: 'body',
    kind: 'insight',
    priority: 'low',
    title: 'Weight stable this week',
    body: 'Your average weight remained stable over the last 7 days.',
    timeLabel: '5 h ago',
    read: false,
    href: '/body-metrics',
    ctaLabel: 'View metrics',
  },
  {
    id: 'n-8',
    category: 'finance',
    kind: 'update',
    priority: 'low',
    title: 'Credit card statement closed',
    body: 'The June statement for R$ 6,750 is available for review.',
    timeLabel: 'Yesterday',
    read: true,
    href: '/monthly-expenses',
    ctaLabel: 'View statement',
  },
  {
    id: 'n-9',
    category: 'system',
    kind: 'update',
    priority: 'low',
    title: 'Weekly summary available',
    body: 'See how your week went across finance, training, and diet.',
    timeLabel: 'Yesterday',
    read: true,
    href: '/',
    ctaLabel: 'Open summary',
  },
  {
    id: 'n-10',
    category: 'goals',
    kind: 'alert',
    priority: 'urgent',
    title: 'Goal "Trip" needs attention',
    body: 'At the current pace, you may not reach the goal by the deadline.',
    timeLabel: '2 days ago',
    read: true,
    href: '/finance-goals',
    ctaLabel: 'Adjust goal',
  },
];
